// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSeverAddress() {
  return window['go']['backend']['App']['GetSeverAddress']();
}

export function WailsShutdown() {
  return window['go']['backend']['App']['WailsShutdown']();
}
