// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSeverAddress():Promise<number>;

export function WailsShutdown():Promise<void>;
