// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParserByURL(arg1) {
  return window['go']['RSSParser']['RSSParser']['ParserByURL'](arg1);
}
