// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gofeed} from '../models';

export function ParserByURL(arg1:string):Promise<gofeed.Feed>;
